# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 00:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('contact_number', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only numbers are allowed.')])),
                ('address', models.TextField()),
            ],
        ),
    ]
