# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 00:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_number',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.')]),
        ),
    ]
