# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 01:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180219_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.')]),
        ),
    ]
